controller_list:
  - name: fake_arm_controller
    type: $(arg fake_execution_type)
    joints:
      - base_joint
      - y_joint
      - uball_joint
      - x_joint
      - mball_joint
      - wrist_joint
      - hand_joint
      - f1_z_pris
      - f1_joint
  - name: fake_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - wrist_joint
      - hand_joint
      - f1_z_pris
      - f1_joint
      - f2_joint
      - f3_joint
      - f4_joint
      - f5_joint
      - f6_joint
      - fe_joint
initial:  # Define initial robot poses.
#  - group: arm
#    pose: home

  []